---

# Projects, Inventories, Inventory Sources, Labels, Credentials, Execution Environments, Job Templates, Workflow Job Templates


### LABELS ###

controller_labels:
  - name: Mapfre2025
    organization: Mapfre2025


### JOB TEMPLATES ###

controller_templates:

  - name: "[SC25] Test Template"
    description: "New Template created as part of SC25"
    job_type: run
    inventory: Config as Code Inventory
    project: Summit25 CICD Project
    playbook: playbooks/test.yml
    credential: "Linux Credential"
    organization: CaC
    labels:
      - Mapfre2025
    # survey_enabled: true
    # survey_spec:
    #   name: <survey_name>
    #   description: <survey_desc>
    #   spec:
    #     - question_name: <question_name>
    #       question_description: <question_desc>
    #       required: true
    #       type: text
    #       max: 50
    #       variable: <var_to_store_answer>
    #       default: <default_answer>
    #       new_question: true
